language: python
matrix:
  include:
  - os: linux
    python: 3.6
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='tests/travis/testing.sh'
  - os: linux
    python: 3.7
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='tests/travis/testing.sh'
  - os: linux
    python: 3.8
    dist: bionic
    env: PIP_CMD='pip install -e .[dev]' TEST_CMD='tests/travis/testing.sh'
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda info -a
install:
- conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
- source activate test-environment
- "$PIP_CMD"
- conda info -a
after_success:
- coveralls
script:
- travis_wait 40 bash $TEST_CMD
notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always
deploy:
  - provider: pypi
    user: __token__
    distributions: sdist bdist_wheel
    on:
      branch: dev
    password:
      secure: BpjyOC2xT3gSrABEE54nihReichfk4XDlyBCq3ZOIi+ndvtjjf6L/JuhjPxzw7V8vhEoNVWRbpe537BVZk2VLebc7vQfSjTdmOdAe3vdC1pk8+VIaAf7nzEB/FU3ce5OsmXNbUpgciUxo2C+VlaNfWpCru/vR/jxUO5/SHB+1/gEXyKMihyubpear6Anv1npzmEsQE7GclM+UzKJv1G8FxqTfjUWiKhnfqsejD6ByjuPAKAD/LZYpzU2kTq1JBi44qw0ARHAIvKLQK32Lz6gx/I9vO9rUNod+J4vGtBY/sjMJLcqzW5ivbInlw86DMF628hoD6J8N2ZefUwU/QlwRQ/HbvMu6rtc3COS6pLMSHV/aUdHVcnnPK4P/Vt37e4j0cj1vD81CsOjjpObRRKxEMilUZxRQ0HtY5K9x8kbamwXPCgxDZpGIoesq0zkSCLujS2I8CpnBldsHPrA/8qP5JW1d17LH1jYe2er3Tz5Oo9Luj7cUsRP2iGeY/Zke2SEBuEwf3TiceeZSEz/kshmZmTNg3xd2hXr9aSRqvEx8hRm6eml1Bt87X6SISChvnkWDominpo/DbG03vvphclWQILGMOGvizez6d6d1mpz2JcB6qfBUY+vy0u1EilA27ABptCnJVbd82WxQcx9IPyQlOPx65+owIB8+Zix8hRe8ig=
    skip_existing: true